name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: cd
      run: cd OrleansWebServer
    - name: ls
      run: ls
    - name: Restore dependencies
      run: dotnet restore OrleansWebServer.sln
    - name: Build
      run: dotnet build OrleansWebServer.sln --no-restore
    - name: Test
      run: dotnet test OrleansWebServer.sln --no-build --verbosity normal
